In [4]:
import pandas as pd
import numpy as np

In [2]:

df = pd.read_csv("/content/drive/MyDrive/DV SKILL /StudentsPerformance.csv")

In [ ]:
categorical_columns = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

In [6]:
df.shape

(1000, 8)

In [7]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [8]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [19]:
subjects = [
    "math score",
    "reading score",
    "writing score"
]

In [20]:
print("STATISTICAL MEASURES")

for subject in subjects:

    print("\nSubject:", subject)

    print("Mean:", df[subject].mean())
    print("Median:", df[subject].median())
    print("Standard Deviation:", df[subject].std())
    print("Q1:", df[subject].quantile(0.25))
    print("Q3:", df[subject].quantile(0.75))

STATISTICAL MEASURES

Subject: math score
Mean: 66.089
Median: 66.0
Standard Deviation: 15.163080096009468
Q1: 57.0
Q3: 77.0

Subject: reading score
Mean: 69.169
Median: 70.0
Standard Deviation: 14.60019193725222
Q1: 59.0
Q3: 79.0

Subject: writing score
Mean: 68.054
Median: 69.0
Standard Deviation: 15.195657010869642
Q1: 57.75
Q3: 79.0